# Generated by Django 4.0.2 on 2022-02-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=20)),
                ('potency', models.CharField(max_length=5)),
                ('duration', models.IntegerField()),
                ('serial', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
    ]
