# Generated by Django 3.2.12 on 2022-02-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=100)),
                ('familia', models.CharField(max_length=100)),
                ('pais_origem', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('floracao', models.CharField(max_length=100)),
                ('tamanho_medio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('solo', models.CharField(max_length=100)),
                ('luminosidade_preferida', models.CharField(max_length=100)),
                ('frequencia_irrigacao', models.CharField(max_length=100)),
            ],
        ),
    ]
